trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'flask-demo'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- task: Docker@2
  inputs:
    containerRegistry: '<service-connection-to-ACR>'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: '<Azure-service-connection-name>'
    azureResourceGroup: '<resource-group>'
    kubernetesCluster: '<cluster-name>'
    namespace: 'default'
    command: apply
    useConfigurationFile: true
    configuration: 'manifests/deployment.yaml'
